### ISSUE TITLE
Webpack production mode chunks issue

### ISSUE THREAD

**Issue by davolcu** [purtuga/esm-webpack-plugin#14]
Hi,

When enabling the optimization mode by chunks on Webpack as follows:

```
optimization: {
    splitChunks: {
        automaticNameDelimiter: '~',
        cacheGroups: {
            commons: {
                test: /[\\/]node_modules[\\/]/,
                chunks: 'all',
            },
        },
    },
},
```

The output file does not have the default export available and returns the following error when trying to load it on the browser:

`build.js:269 Uncaught TypeError: Cannot read property 'default' of undefined`

I can't find any work-around to combine this plugin with the Webpack optimization feature

**Comment by purtuga** [comment]
Hi @darionco .
It hard to determine what the issue might be and whether this plugin may be able to support your use case just based on the info. you posted

Could you create a quick test project that has a setup in place that demonstrates the problem?

**Comment by darionco** [comment]
I think you got the wrong dev ;)

**Comment by davolcu** [comment]
@purtuga I've been able to reproduce it on a test project. I've added the browser-sync dependency to mock a server and the bug happens anyway. 

Here's the link to the GitHub repository of the test project: https://github.com/davolcu/esm-test-app. Just run `npm run start` and you should be able to reproduce the error.

**Comment by davolcu** [comment]
ping @purtuga

**Comment by purtuga** [comment]
Hi @davolcu sorry for the delay, but I have not yet had a chance to look into this. Thank you for the sample project - that will help allot by just getting the debugging going. I will come back soon

**Comment by purtuga** [comment]
Spent some time debugging this. Again, thanks for the test repo - that helps allot. 
Ultimately, what you are attempting todo I don't think is possible. when webpack's chuncking kicks in, just about no exports are actually available/loaded because they are loaded async (deferred), thus why `LIB` is `undefined`. 

In your case, a possible solution is have a `index.js`. file whose sole purpose is to export a "loader method", and that loader method uses dynamic imports to then load your code. I did this in a fork of the test repo you provided and it seems to work:

```javascript
// file: vue/index.js

export const loadIndexComponent = async () => {
    return await import('./index.vue');
};
export default loadIndexComponent;
```

I then changed your HTML file to the following:
```javascript
import loadIndexComponent from "./index.js";

    loadIndexComponent().then(Index => {
      // Vue instance to create the app component
      new Vue({
          el: '.index-container',
          delimiters: ['${', '}'],
          components: {
              Index
          },
          data() {
              return {
                  text: "Hello world"
              };
          }
      });
    });
```

This got around the problem that this Webpack plugin is encountering. your test project seems to have some other error coming out that I don't think are related to my plugin.

I pushed my changes to you test repo (had to make some other changes) so that you can check it out - here is a diff:

https://github.com/davolcu/esm-test-app/compare/master...purtuga:master


Closing this for now, but if you feel three is still an issue, please feel free to reopen it.
