### ISSUE TITLE
Dynamic Imports with target: node

### ISSUE THREAD

**Issue by reed-jones** [purtuga/esm-webpack-plugin#17]
Dynamic imports (such as async routes in vue-router)
```
{
  path: '/',
  component: () => import('./components/HomePage.vue')
}
```
aren't outputting ESM when targetting node. I'm using node v14.8.0 with `type: 'module'` in package.json, so this throws an error since 'require' is not defined.

Repro: https://github.com/reed-jones/esm-webpack-repro

The file being dynamically imported 'external.js' is still commonjs https://github.com/reed-jones/esm-webpack-repro/blob/master/dist/0.main.js and the code to import it, is still using 'require' despite the rest being exported as ESM. https://github.com/reed-jones/esm-webpack-repro/blob/ba0f3b7f737324a0bae9222862edb869570b7483/dist/main.js#L45

**Comment by purtuga** [comment]
Hi @reed-jones . 
I will look at this soon. At first glance, I'm thinking that is ok - this plugin I don't think is meant to address dynamic imports because the files output there are considered internal to webpack. Thanks for providing the repo - that will help allot in trying to see what is going on.

**Comment by reed-jones** [comment]
Awesome, thanks for taking a look. Hopefully this can work, but if not I'll look at other strategies. Let me know if there is anything else I can do to help here. 🙂👍

**Comment by purtuga** [comment]
Hi @reed-jones in looking at your webpack configuration, it does not look like its setup correctly - you don't have the required entries in the `output` that is needed to be able to this plugin to generate a ES Module. This message is output when you run it:

```
[EsmWebpackPlugin] output.library is expected to be set!
```

In order for your build to output an ES6 module with this plugin, you must setup output to be `var` - [see instructions here](https://github.com/purtuga/esm-webpack-plugin#usage) and then also define a `library` value. I made this change to your webpack config:

```diff
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
+    libraryTarget: 'var',
+   library: 'LIB'
  },
```
And this allowed the build to output the necessary correct exports to the end of the output file. 


**Re:** output of CommonJS dynmaic chunk

Your webpack config. has a target of `node` which [Webpack documentation](https://webpack.js.org/configuration/target/) indicates that `require` will be used to load chunks - my plugin is not going to touch that part. You may want to look further into this Webpack documentation - there seems to be a way to use a function for `target` in order to provide custom loaders (maybe?)

I hear that the next version of Webpack may introduce a target of `esm`, which will hopefully remove the need for my plugin. 

I'm closing this out for now, but if you feel there is still a potential issue here, please feel free to re-open it 😃

**Comment by reed-jones** [comment]
woops, I have that setup (library/libraryTarget) in my actual project, just missed it in the repro. Thanks for looking at this though. I missed that `target` can be a function, I'll give that a shot. Hopefully I can copy a custom target using the built in `node` as a starting point... https://github.com/webpack/webpack/blob/3f12b0fa27e2e6e5c96afd685faa7162bf75ee8a/lib/WebpackOptionsApply.js#L100

Also thanks for the plugin 👍 works great, even if it turns out not to be the full solution for my exact `esm` problem 😃 .
