### ISSUE TITLE
How about ESM imports?

### ISSUE THREAD

**Issue by geekox86** [purtuga/esm-webpack-plugin#5]
Excellent work.

I am wondering how can we preserve imports of other ESM module files (not bundled) with ESM syntax to enable tree shaking by consumers?

Thank you!

**Comment by purtuga** [comment]
That’s one of the drawbacks of this plugin approach to creating an ESM package. It simply adds export statements to the normally generated bundle from webpack, so it’s really not changing the way modules are bundled - which what would be needed in order to truly provide a tree-shakeable bundle.

My guess is that can only happen when webpack itself starts to support a target of ESM - which I think they are planning on. I can imagine it not being an easy problem to solve because the ECMAScript Module standard does not have the concept of bundling, so webpack still needs to do some of that in order to include multiple files into one output package.

My advice is to use/reference a library’s Source when developing in a project that has a build/bundled in the pipeline. Use the ESM output that this plugin generates when needing to reference the library at runtime (ex. From the browser) as an external resource.

Hope I made sense in my response 😄

Paul

-- sent from mobile

**Comment by purtuga** [comment]
FYI... I think your question here should be added to the README file under the FAQ so that others are ware of the caveat. I will do that soon.

**Comment by purtuga** [comment]
I just noticed the following in your question:

> ...other ESM module files (not bundled) ...

I'm a bit confused by the "not bundled"... Can you explain this a little further? and better yet - can you provide code samples as to what you would expect your final output ESM bundle to look like?

**Comment by purtuga** [comment]
When you get a chance, let me know about my question above. In the mean time, I have added an FAQ to the README file to more clearly call out the limitations.
